config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views


# http://127.0.0.1:8000/
urlpatterns = [
    path("admin/", admin.site.urls),  # http://127.0.0.1:8000
    path("pybo/", include("pybo.urls")),
    path("common/", include("common.urls")),  # dev_13
    path("", base_views.index, name="index"),  # dev_13
]

pybo/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views, question_views, answer_views


app_name = "pybo"

## http://127.0.0.1:8000/pybo/5/
urlpatterns = [
    path("", base_views.index, name="index"),
    # http://127.0.0.1:8000/pybo/<int:question_id>/
    path("<int:question_id>/", base_views.detail, name="detail"),  #  dev_3
    path(
        "answer/create/<int:question_id>/",
        answer_views.answer_create,
        name="answer_create",
    ),  # dev_5
    path(
        "question/create/", question_views.question_create, name="question_create"
    ),  # dev_9
    path(
        "question/modify/<int:question_id>/",
        question_views.question_modify,
        name="question_modify",
    ),  # dev_17
    path(
        "question/delete/<int:question_id>/",
        question_views.question_delete,
        name="question_delete",
    ),  # dev_17
    path(
        "answer/modify/<int:answer_id>/",
        answer_views.answer_modify,
        name="answer_modify",
    ),  # dev_18
    path(
        "answer/delete/<int:answer_id>/",
        answer_views.answer_delete,
        name="answer_delete",
    ),  # dev_18
    path(
        "question/vote/<int:question_id>/",
        question_views.question_vote,
        name="question_vote",
    ),  # dev_19
    path(
        "answer/vote/<int:answer_id>/",
        answer_views.answer_vote,
        name="answer_vote",
    ),  # dev_19 답변 추천
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# dev_2


# 하나의 질문에는 무수히 많은 답변이 등록


class Question(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_question"
    )  # dev_16
    subject = models.CharField(max_length=100)
    content = models.TextField()  # 글자 수에 제한이 없는 텍스트는 TextField를 사용한다
    create_date = models.DateTimeField()
    # dev_17
    # modify_date 칼럼에 null을 허용함
    # blank=True는 form.is_valid()를 통한 입력 데이터 검증 시 값이 없어도 된다는 의미
    modify_date = models.DateField(null=True, blank=True)  # 수정 일시
    voter = models.ManyToManyField(
        User, related_name="voter_question"
    )  # 추천인 추가 dev_19

    def __str__(self):
        return self.subject


# class    QuestionVoter:
#     voter =  models.ForeignKey(
#         User, on_delete=models.CASCADE, related_name="author_question"
#     )
#     question =  models.ForeignKey(
#         Question , on_delete=models.CASCADE, related_name="author_question"
#     )
#     modify_date = models.DateField(null=True, blank=True)


class Answer(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_answer"
    )  # dev_16
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
    )
    content = models.TextField()
    create_date = models.DateTimeField()
    # dev_17
    modify_date = models.DateField(null=True, blank=True)  # 수정 일시
    # dev_19
    voter = models.ManyToManyField(User, related_name="voter_answer")


# q=Question.objects.get(id=4)
# q.answer_set.all()
# <QuerySet [<Answer: Answer object (3)>, <Answer: Answer object (4)>, <Answer: Answer object (8)>]>

# .answer_set.all()    # 4.answer_set.all() # 역방향 참조
# Question .answers.all()    # 4.answers.all() # 역방향 참조

pybo/forms.py
from django import forms

from pybo.models import Answer, Question


# dev_9
class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question  # form 과 모델을 연결
        fields = ["subject", "content"]  # QuestionForm에서 사용할 Question 모델의 속성


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer  # form 과 모델을 연결
        fields = ["content"]
        labels = {"content": "답변내용"}

pybo/views/answer_views.py
from urllib import response
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render

from pybo.forms import AnswerForm, QuestionForm
from pybo.models import Answer, Question
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# dev_9
@login_required(login_url="common:login")  # dev_16
def answer_create(request, question_id):
    """
    pybo 답변등록
    """

    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # dev_16 현재 로그인한 계정의 User 모델 객체
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect("pybo:detail", question_id=question.id)

    else:
        return HttpResponseNotAllowed("Only POST is possible.")

    context = {"question": question, "form": form}
    return render(request, "pybo/question_detail.html", context)


# dev_18
@login_required(login_url="common:login")
def answer_modify(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect("pybo:detail", question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)

    context = {"answer": answer, "form": form}
    return render(request, "pybo/answer_form.html", context)


@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, "삭제권한이 없습니다")
    else:
        answer.delete()

    return redirect("pybo:detail", question_id=answer.question.id)


@login_required(login_url="common:login")
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        messages.error(request, "본인이 작성한 글은 추천할수 없습니다.")
    else:
        answer.voter.add(request.user)

    return redirect("pybo:detail", question_id=answer.question.id)

pybo/views/base_views.py
from urllib import response
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render

from pybo.forms import AnswerForm, QuestionForm
from pybo.models import Answer, Question
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q


# http://127.0.0.1:8000/pybo
# dev_20 검색 추가
def index(request):

    # ?kw=홍길동&page=1
    page = request.GET.get("page", "1")  # 페이지
    kw = request.GET.get("kw", "")  # 검색어

    # select * from question , user where ~~~;
    question_list = Question.objects.order_by("-create_date")

    # dev_20
    if kw:
        # select disctict * from question,user where subject like "%홍길동%"
        question_list = question_list.filter(
            Q(subject__icontains=kw)  # 제목검색
            | Q(content__icontains=kw)  # 내용 검색
            | Q(answer__content__icontains=kw)  # 답변내용 검색
            | Q(author__username__icontains=kw)  # 질문 글쓴이 검색
            | Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    # dev_20 수정
    context = {"question_list": page_obj, "page": page, "kw": kw}

    # 리액트와 차이 = 다시 그린다.(클라이언트 입장) =  httpRespose 객체로 만든후에 html 태그를 클라이언트한테 보낸다.
    return render(request, "pybo/question_list.html", context)


# http://127.0.0.1:8000/pybo/<int:question_id>/
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)

    context = {"question": question}
    return render(request, "pybo/question_detail.html", context)

    # path(
    #     "answer/create/<int:question_id>/", views.answer_create, name="answer_create"
    # ),  # dev_5

pybo/views/question_views.py
from urllib import response
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render

from pybo.forms import AnswerForm, QuestionForm
from pybo.models import Answer, Question
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url="common:login")  # dev_16
def question_create(request):

    print(request.POST.get("content"))

    if request.method == "POST":

        form = QuestionForm(request.POST)

        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # dev_16
            question.create_date = timezone.now()
            question.save()
            return redirect("pybo:index")

    else:
        form = QuestionForm()

    context = {"form": form}
    return render(request, "pybo/question_form.html", context)


# dev_17
@login_required(login_url="common:login")
def question_modify(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect("pybo:detail", question_id=question.id)
    else:
        form = QuestionForm(instance=question)

    context = {"form": form}
    return render(request, "pybo/question_form.html", context)


@login_required(login_url="common:login")
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:
        messages.error(request, "삭제권한이 없습니다")
        return redirect("pybo:detail", question_id=question_id)

    question.delete()
    return redirect("pybo:index")


@login_required(login_url="common:login")
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.user == question.author:
        messages.error(request, "본인이 작성한 글은 추천할수 없습니다.")
    else:
        question.voter.add(request.user)

    return redirect("pybo:detail", question_id=question.id)

templates/pybo/answer_form.html
<!--dev_18-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock content %}

templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- message 표시 dev_17 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}    
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            
            <div class="d-flex justify-content-end">
                
                <!--dev_18-->
                {% if question.modify_date  %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div >
                        {{ question.modify_date }}
                    </div>
                </div>
                {% endif %}                    
                
                <!--dev_16-->
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div >
                        {{ question.create_date }}
                    </div>
                </div>

            </div>
            <!--로그인한 사용자와 글쓴이가 동일한 경우에만 노출 dev_17-->
            <div class="my-3">
                <!--dev_19-->
                <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}" class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>

                {% if request.user == question.author %}
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'pybo:question_modify' question.id %}">수정</a>    
                    <a class="delete btn btn-sm btn-outline-secondary" href="javascript:void(0)" data-uri="{% url 'pybo:question_delete' question.id  %}" >삭제</a>  
                {% endif %}                
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <!--dev_18-->                
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modifed at</div>
                    <div >
                        {{ answer.modify_date }}
                    </div>
                </div>
                {% endif %}                   

                <!--dev_16-->
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div >
                        {{ answer.create_date }}
                    </div>
                </div>
            </div>
            <!--dev_18-->
            <div class="my-3">
                <!--dev_19-->
                <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}" class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>                 
                
                {% if request.user == answer.author %}
                    <a href=" {% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href=" {% url 'pybo:answer_delete' answer.id %}" class="btn btn-sm btn-outline-secondary">삭제</a>
                {% endif %}     
           </div>

        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start {{form.as_p}}-->
        {% if form.errors  %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>            
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <!-- dev_16 -->
            <textarea  
            {% if not user.is_authenticated  %}
                disabled
            {% endif %}
                 name="content" id="content" class="form-control" rows="10"></textarea>

        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% block script%}
<script type='text/javascript'>
    
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    
    
    const recommand_elements = document.getElementsByClassName("recommend");    
    Array.from(recommand_elements).forEach(function(element) {
            element.addEventListener('click', function() {
            if(confirm("정말로 추전하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

</script>
{% endblock script %}   

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
     <!-- form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL이 기본 action으로 설정-->
  
     <form method="post">
        {% csrf_token %}
       
       <!-- 오류표시 Start {{form.as_p}}-->
        {% if form.errors  %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>            
        {% endif %}
       <!-- 오류표시 End -->
       <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value={{form.subject.value|default_if_none:''}} >
       </div>
       <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{form.content.value|default_if_none:''}}</textarea>
        </div>       
        <button type="submit" class="btn btn-primary" >저장하기</button>
    </form>
</div>    
{% endblock content %}
    

templates/pybo/question_list.html
{% extends 'base.html' %}

{% block content %}    
<div class="container my-3">
    
    <!--dev_20-->
    <div class="row my-3"> 
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>        
    </div>
    
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%" >제목</th>
            <th>글쓴이</th> <!--dev 16-->
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center"><!--dev16 -->
            <td>{{ forloop.counter }}</td>
            <td class="text-start"><!--dev16 -->
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                <!--dev_12-->
                <span class="text-danger samll mx-2">{{ question.answer_set.count}}</span>
            </td>
            <td>{{ question.author.username }}</td> <!--dev16 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td> <!--dev16 3->4 -->
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        
        {% if question_list.has_previous %}
            <li class="page-item">
                <!--dev_20-->
                <a class="page-link" href="javascript:void(0)" data-page="{{question_list.previous_page_number}}" >이전</a>
            </li> 
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">이전</a>
            </li>
        {% endif %}
        <!--페이지리스트-->        
        {% for page_number   in  question_list.paginator.page_range  %}                        
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}             
            {% if page_number == question_list.number  %}
                <li class="page-item active" aria-current="page">
                    <!--dev_20-->
                    <a  class="page-link" href="javascript:void(0)" data-page="{{page_number}}">{{page_number}}</a>
                </li>
            {% else %}
                <li class="page-item " aria-current="page">
                    <!--dev_20-->
                    <a class="page-link" href="javascript:void(0)" data-page="{{page_number}}">{{page_number}}</a>
                </li>
            {% endif %} 
            {% endif %}
        {% endfor %}
        
        <!--다음 페이지-->
        {% if question_list.has_next %}
            <li class="page-item">
                <!--dev_20-->
                <a class="page-link" href="javascript:void(0)" data-page="{{question_list.next_page_number}}" >다음</a>
            </li> 
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">다음</a>
            </li>
        {% endif %}  
    <!-- 페이징처리 끝 -->        
    </ul>
</div>
<!--dev_20 page와 kw를 동시에 GET으로 요청할 수 있는 searchForm을 추가-->
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:''}}">
    <input type="hidden" id="page" name="page" value="{{page}}">
</form>
{% endblock content %}

{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });

    //<button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>

    //<form id="searchForm" method="get" action="{% url 'index' %}">
    //    <input type="hidden" id="kw" name="kw" value="홍길동">
    //    <input type="hidden" id="page" name="page" value="1">
    //</form> 
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
</script>

{% endblock script %}