common/urls.py
# dev_19
from django.urls import path
from django.contrib.auth import views as auth_view

from common import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_view.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),  # dev_13
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),  # dev_15
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views


# http://127.0.0.1:8000/
urlpatterns = [
    path("admin/", admin.site.urls),  # http://127.0.0.1:8000
    path("pybo/", include("pybo.urls")),
    path("common/", include("common.urls")),  # dev_13
    path("", base_views.index, name="index"),  # dev_13
]

pybo/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views, question_views, answer_views


app_name = "pybo"

## http://127.0.0.1:8000/pybo/5/
urlpatterns = [
    path("", base_views.index, name="index"),
    # http://127.0.0.1:8000/pybo/<int:question_id>/
    path("<int:question_id>/", base_views.detail, name="detail"),  #  dev_3
    path(
        "answer/create/<int:question_id>/",
        answer_views.answer_create,
        name="answer_create",
    ),  # dev_5
    path(
        "question/create/", question_views.question_create, name="question_create"
    ),  # dev_9
    path(
        "question/modify/<int:question_id>/",
        question_views.question_modify,
        name="question_modify",
    ),  # dev_17
    path(
        "question/delete/<int:question_id>/",
        question_views.question_delete,
        name="question_delete",
    ),  # dev_17
    path(
        "answer/modify/<int:answer_id>/",
        answer_views.answer_modify,
        name="answer_modify",
    ),  # dev_18
    path(
        "answer/delete/<int:answer_id>/",
        answer_views.answer_delete,
        name="answer_delete",
    ),  # dev_18
    path(
        "question/vote/<int:question_id>/",
        question_views.question_vote,
        name="question_vote",
    ),  # dev_19
    path(
        "answer/vote/<int:answer_id>/",
        answer_views.answer_vote,
        name="answer_vote",
    ),  # dev_19 답변 추천
]

pybo/views/base_views.py
from urllib import response
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, redirect, render

from pybo.forms import AnswerForm, QuestionForm
from pybo.models import Answer, Question
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q


# http://127.0.0.1:8000/pybo
# dev_20 검색 추가
def index(request):

    # ?kw=홍길동&page=1
    page = request.GET.get("page", "1")  # 페이지
    kw = request.GET.get("kw", "")  # 검색어

    # select * from question , user where ~~~;
    question_list = Question.objects.order_by("-create_date")

    # dev_20
    if kw:
        # select disctict * from question,user where subject like "%홍길동%"
        question_list = question_list.filter(
            Q(subject__icontains=kw)  # 제목검색
            | Q(content__icontains=kw)  # 내용 검색
            | Q(answer__content__icontains=kw)  # 답변내용 검색
            | Q(author__username__icontains=kw)  # 질문 글쓴이 검색
            | Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    # dev_20 수정
    context = {"question_list": page_obj, "page": page, "kw": kw}

    # 리액트와 차이 = 다시 그린다.(클라이언트 입장) =  httpRespose 객체로 만든후에 html 태그를 클라이언트한테 보낸다.
    return render(request, "pybo/question_list.html", context)


# http://127.0.0.1:8000/pybo/<int:question_id>/
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)

    context = {"question": question}
    return render(request, "pybo/question_detail.html", context)

    # path(
    #     "answer/create/<int:question_id>/", views.answer_create, name="answer_create"
    # ),  # dev_5

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include 'navbar.html' %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
            <!-- 필드 오류 -->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <!--dev_13-->
                    
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}    
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}                   
                </li>
                <!--dev_15-->
                <li>
                    {% if not user.is_authenticated %}
                        <a href=" {% url 'common:signup' %}" class="nav-link" >회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>